# Generated by Django 5.2.6 on 2025-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
