# Generated by Django 5.2.6 on 2025-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
