# Generated by Django 5.2.6 on 2025-09-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_tour_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.AddField(
            model_name='tour',
            name='budget_current',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='budget_detail',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_detail',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='min_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ToursImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
    ]
