# Generated by Django 5.2.6 on 2025-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_tour_price_remove_tour_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='budget_current',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='budget_detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_detail',
            field=models.TextField(default=''),
        ),
    ]
