# Generated by Django 5.2.6 on 2025-09-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_tour_budget_current_alter_tour_budget_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
