# Generated by Django 5.2.6 on 2025-09-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
