# Generated by Django 5.2.6 on 2025-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tour',
            name='numberOfPeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_url',
            field=models.TextField(default=''),
        ),
    ]
