# Generated by Django 5.2.6 on 2025-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_tour_difficulty_tour_location_tour_numberofpeople_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='numberOfPeople',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='thumbnail_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
