# Generated by Django 5.2.6 on 2025-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_rename_toursimage_tourimages_remove_tour_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
