# Generated by Django 5.2.6 on 2025-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_tour_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.TextField(blank=True, default=''),
        ),
    ]
