# Generated by Django 5.2.6 on 2025-10-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_tour_highlights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='tour',
            name='budget_current',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='budget_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='min_budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
