# Generated by Django 5.2.6 on 2025-10-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travel.tour'),
        ),
    ]
