# Generated by Django 5.2.6 on 2025-10-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_comment_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
