# Generated by Django 5.2.6 on 2025-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_contact_status_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
