# Generated by Django 5.2.6 on 2025-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
